# Generated by Django 4.2 on 2026-07-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faenas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad', models.IntegerField(default=0, help_text='Cantidad en unidades')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('unidad', 'Unidades'), ('libra', 'Libras')], default='kg', max_length=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='faenas.faena')),
            ],
            options={
                'verbose_name': 'Item de Recepción',
                'verbose_name_plural': 'Items de Recepción',
            },
        ),
    ]
