# Generated by Django 4.2 on 2026-07-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capitanes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_faena', models.CharField(editable=False, max_length=50, unique=True)),
                ('fecha_salida', models.DateField()),
                ('fecha_entrada_est', models.DateField()),
                ('fecha_entrada_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En Curso'), ('RECIBIDO', 'Recibido'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('deuda_inicial', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('deuda_descontada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deuda_pendiente', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('saldo_favor_capitan', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capitan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faenas', to='capitanes.capitan')),
            ],
            options={
                'verbose_name': 'Faena',
                'verbose_name_plural': 'Faenas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gasolina', 'Gasolina'), ('hielo', 'Hielo'), ('carnada', 'Carnada'), ('viveres', 'Víveres'), ('material', 'Material de Pesca'), ('otros', 'Otros')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='faenas.faena')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['tipo'],
            },
        ),
    ]
