# Generated by Django 4.2 on 2026-07-10 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faenas', '0001_initial'),
        ('embarcaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faena',
            name='despachador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faenas_despachadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faena',
            name='embarcacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faenas', to='embarcaciones.embarcacion'),
        ),
        migrations.AddField(
            model_name='faena',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faenas_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
